# Generated by Django 4.2.7 on 2023-11-26 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 28, 53, 742850, tzinfo=datetime.timezone.utc)),
        ),
    ]
