# Generated by Django 4.2.7 on 2023-11-27 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 5, 22, 23, 298517, tzinfo=datetime.timezone.utc)),
        ),
    ]
