# Generated by Django 4.2.7 on 2023-12-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
