# Generated by Django 4.2.7 on 2023-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_like_count_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
