# Generated by Django 4.2.7 on 2023-12-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_like_user_post_likes_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
