# Generated by Django 4.2.7 on 2023-12-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
